name: Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    tags:
      - '*'
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.runs-on }}
    strategy:
      fail-fast: false
      matrix:
        runs-on:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          python -m pip install -r requirements.txt

      - name: Run tests
        run: python -m pytest -s -v .
        env:
          # Needed for coveralls:
          GITHUB_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

# vim:set et sts=2:
